name: guv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint (no_std)
      run: cargo clippy --verbose
    - name: Lint (all features)
      run: cargo clippy --verbose --all-features
    - name: Build (no_std)
      run: cargo build --verbose --release
    - name: Build (all features)
      run: cargo build --verbose --release --features std
    - name: Run tests
      run: cargo test --verbose --all-features
