name: guv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Formatting
      run: cargo fmt --check

    - name: Clippy (no_std)
      run: cargo clippy --verbose
    - name: Clippy (std)
      run: cargo clippy --verbose --features="std"
    - name: Clippy (fixed, no_std)
      run: cargo clippy --verbose --features="fixed"
    - name: Clippy (float, no_std)
      run: cargo clippy --verbose --features="float"
    - name: Clippy (fixed, std)
      run: cargo clippy --verbose --features="fixed,std"
    - name: Clippy (float, std)
      run: cargo clippy --verbose --features="float,std"
    - name: Clippy (all features)
      run: cargo clippy --verbose --all-features

    - name: Build (no_std)
      run: cargo build --verbose --release
    - name: Build (std)
      run: cargo build --verbose --release --features="std"
    - name: Build (fixed, no_std)
      run: cargo build --verbose --release --features="fixed"
    - name: Build (float, no_std)
      run: cargo build --verbose --release --features="float"
    - name: Build (fixed, std)
      run: cargo build --verbose --release --features="fixed,std"
    - name: Build (float, std)
      run: cargo build --verbose --release --features="float,std"
    - name: Build (all features)
      run: cargo build --verbose --release --all-features

    - name: Test (fixed, std)
      run: cargo test --verbose --features="fixed,std"
    - name: Test (float, std)
      run: cargo test --verbose --features="float,std"
    - name: Test Release (fixed, std)
      run: cargo test --verbose --release --features="fixed,std"
    - name: Test Release (float, std)
      run: cargo test --verbose --release --features="float,std"
